/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_URL.split('.')[0].split('//')[1]
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY